name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        path: flaskapp
        
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        ssh-keyscan -H ${{ secrets.EC2_HOST }} 2>/dev/null >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Decode and Setup SSH Key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd cd ${{ github.workspace }}/flaskapp
          git pull origin main
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker build --no-cache -t myapp .
          sudo docker run -d -p 5000:5000 myapp
        EOF
